### ISSUE TITLE
file not found 

### ISSUE THREAD

**Issue by ebarberena2556** [robleseli/matplotlib-practice#1]
import numpy as np
import matplotlib.pyplot as plt

data_file = np.genfromtxt('data_file.txt',delimiter=',')
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    data_file = np.genfromtxt('data_file.txt',delimiter=',')
  File "C:\Users\eduar\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\npyio.py", line 1922, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "C:\Users\eduar\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "C:\Users\eduar\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: data_file.txt not found.

**Comment by ebarberena2556** [comment]
import numpy as np
import matplotlib.pyplot as plt

data_file = np.genfromtxt('data_file.txt',delimiter=',')




this is the code i used

**Comment by robleseli** [comment]
try this:

import numpy as np
data = np.loadtxt("./data_file.txt", delimiter = ",")

print("First 5 rows:\n", data[:5])


we're not using the matplotlib functions right now so it's okay to exclude them for now. we're using the loadtxt function instead. i am also changing the name of the variable from data_file to just data, as sometimes there can be an issue when stuff shares a variable/file name. lastly, we're printing the first 5 lines of the data in order to see how it looks like, and then from there we'll figure out our approach to use $ as an additional delimiter.

**Comment by robleseli** [comment]
download pycharm community version https://www.jetbrains.com/pycharm/download/#section=windows
this will help you write code so you won't have to lose code in the IDLE. 

while i try to solve the problem try the pandas approach:

import pandas as pd
data = pd.read_csv(" (filename goes here).txt ", sep = " (deliminter goes here) ")
print (data)

**Comment by ebarberena2556** [comment]
"C:\Users\eduar\OneDrive\Desktop\g823_2022175_1523.log"

**Comment by robleseli** [comment]
vairablename = np.loadtxt("C:\Users\eduar\OneDrive\Desktop\g823_2022175_1523.log")

**Comment by ebarberena2556** [comment]
import numpy as np
variable = np.loadtxt(u"C:\\Users\\eduar\\OneDrive\\Desktop\\g823_2022175_1523.log",
                      delimiter="$", " ", ",")
SyntaxError: positional argument follows keyword argument


new code and new issue for the correction of code.

**Comment by robleseli** [comment]
import numpy as np
variable = np.loadtxt(u"C:\Users\eduar\OneDrive\Desktop\g823_2022175_1523.log")
