### ISSUE TITLE
friday 7/8/2022 code update semi-working, just need to fix scatter point sizes, add subplot and label everything 

### ISSUE THREAD

**Issue by robleseli** [robleseli/matplotlib-practice#4]

**Comment by ebarberena2556** [comment]
import numpy as np
import matplotlib.pyplot as plt



filename = 'g823_2022175_1523.log'

field_value_list = []
signal_value_list = []
for line in open(filename,'r'):
    split_line = line.split(',')
    field_value_str = split_line[0][2:]
    field_value= float(field_value_str)
    field_value_list.append(field_value)
    signal_value_str = split_line[1].replace('\n','')
    signal_value = int(signal_value_str)
    signal_value_list.append(signal_value)

    
field_value_array = np.array(field_value_list)
signal_value_array = np.array(signal_value_list)

count = np.count_nonzero(field_value_array)
print(count)
5575


x_axis_times = np.linspace(start = 0, stop = 558, num = 5575)

plt.plot(field_value_array)
[<matplotlib.lines.Line2D object at 0x000002011A776DA0>]
plt.show()



ax.set_xlabel('|B[nT]')

plt.scatter(x_axis_times, field_value_array)
<matplotlib.collections.PathCollection object at 0x000002011A610220>
plt.show()

**Comment by ebarberena2556** [comment]
![scatterplot first try](https://user-images.githubusercontent.com/107439936/178021639-7def6ca9-4e33-40cc-bf97-90f99deb6ff2.png)

**Comment by robleseli** [comment]
changed size of plot to s=5

**Comment by ebarberena2556** [comment]
import numpy as np
import matplotlib.pyplot as plt

filename = 'g823_2022175_1523.log'

field_value_list = []
signal_value_list = []
for line in open(filename,'r'):
    split_line = line.split(',')
    field_value_str = split_line[0][2:]
    field_value = float(field_value_str)
    field_value_list.append(field_value)
    signal_value_str = split_line[1].replace('\n','')
    signal_value = int(signal_value_str)
    signal_value_list.append(signal_value)

field_value_array = np.array(field_value_list)
signal_value_array = np.array(signal_value_list)

count = len(field_value_array)
print(count)

x_axis = np.linspace(start = 0, stop = count/10, num = count)

plt.xlabel('time since start of transect[sec]')

plt.ylabel('|B|[nT]')

plt.scatter(x_axis, field_value_array, s=5)

y = len(signal_value_array)
print(y)

**Comment by ebarberena2556** [comment]
import numpy as np
import matplotlib.pyplot as plt

filename = 'g823_2022175_1523.log'

field_value_list = []
signal_value_list = []
for line in open(filename,'r'):
    split_line = line.split(',')
    field_value_str = split_line[0][2:]
    field_value = float(field_value_str)
    field_value_list.append(field_value)
    signal_value_str = split_line[1].replace('\n','')
    signal_value = int(signal_value_str)
    signal_value_list.append(signal_value)

field_value_array = np.array(field_value_list)
signal_value_array = np.array(signal_value_list)

count = len(field_value_array)


x_axis = np.linspace(start = 0, stop = count/10, num = count)

plt.xlabel('time since start of transect[sec]')

plt.ylabel('|B|[nT]')

plt.scatter(x_axis, field_value_array, s=5)


y = len(signal_value_array)
print(y)


x = np.linspace(start = 0, stop = y/10, num = y)

plt.ylabel('reported signal strength')

plt.scatter(x, signal_value_array, s=5)

**Comment by ebarberena2556** [comment]
finished code 


import numpy as np
import matplotlib.pyplot as plt

filename = 'g823_2022175_1523.log'

field_value_list = []
signal_value_list = []
for line in open(filename,'r'):
    split_line = line.split(',')
    field_value_str = split_line[0][2:]
    field_value = float(field_value_str)
    field_value_list.append(field_value)
    signal_value_str = split_line[1].replace('\n','')
    signal_value = int(signal_value_str)
    signal_value_list.append(signal_value)

field_value_array = np.array(field_value_list)
signal_value_array = np.array(signal_value_list)

count = len(field_value_array)


x_axis = np.linspace(start = 0, stop = count/10, num = count)




y = len(signal_value_array)
print(y)


x = np.linspace(start = 0, stop = y/10, num = y)


fig,(ax1,ax2)= plt.subplots(2,1)

ax1.scatter(x_axis, field_value_array, s=1)
ax1.set_ylabel('|B|[nT]')


ax2.scatter(x, signal_value_array, s=1)
ax2.set_xlabel('time since start of transect [sec]')
ax2.set_ylabel('reported signal strength')


plt.show()

**Comment by robleseli** [comment]
finished code

import numpy as np
import matplotlib.pyplot as plt

filename = 'g823_2022175_1523.log'

field_value_list = []
signal_value_list = []
for line in open(filename,'r'):
split_line = line.split(',')
field_value_str = split_line[0][2:]
field_value = float(field_value_str)
field_value_list.append(field_value)
signal_value_str = split_line[1].replace('\n','')
signal_value = int(signal_value_str)
signal_value_list.append(signal_value)

field_value_array = np.array(field_value_list)
signal_value_array = np.array(signal_value_list)

count = len(field_value_array)

x_axis = np.linspace(start = 0, stop = count/10, num = count)

y = len(signal_value_array)
print(y)

x = np.linspace(start = 0, stop = y/10, num = y)

fig,(ax1,ax2)= plt.subplots(2,1)

ax1.scatter(x_axis, field_value_array, s=1)
ax1.set_ylabel('|B|[nT]')

ax2.scatter(x, signal_value_array, s=1)
ax2.set_xlabel('time since start of transect [sec]')
ax2.set_ylabel('reported signal strength')

plt.show()

**Comment by ebarberena2556** [comment]
[magplotting1.py.txt](https://github.com/robleseli/matplotlib-practice/files/9087173/magplotting1.py.txt)
